server:
  port: 9010

spring:
  application:
    name: enterprise-manager
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  consumer:
    group-id: enterprise-manager

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# API Clients configuration
feign:
  clients:
    message-publisher:
      name: MESSAGE-PUBLISHER
      path: /api/message-publisher
    auth-manager:
      name: AUTH-MANAGER
      path: /api/auth-manager
    project-manager:
      name: PROJECT-MANAGER
      internal-path: /internal/project-manager
    user-manager:
      name: USER-MANAGER
      path: /api/user-manager

app:
  data:
    invite-template-name: enterprise-invite
    delete-init-notification-template-name: enterprise-delete-init
    enterprise-delete-request-template-name: delete-enterprise-request
    kolate-support-email: suriya@kolate.ai
