server:
  port: 9090

spring:
  application:
    name: asset-manager
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    allow-bean-definition-overriding: true

kafka:
  consumer:
    group-id: asset-manager

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

cloud:
  aws:
    s3:
      bucket: kolate-web-app-assets-dev
    credentials:
      access-key: your_aws_access_key_here
      secret-key: your_aws_secret_key_here
    region:
      static: us-west-2

cdn:
  base:
    url: https://cdn-dev.kolate.ai/
